### ISSUE TITLE
Instance CRD

### ISSUE THREAD

**Issue by Crevil** [lunarway/postgresql-controller#3]
In time a `PostgreSQLInstance` CRD could be a great way for developers to get new instances available.

This is only though out to be a way to create AWS RDS instances. We are not thinking running our own databases with this setup.

A possible model could be the following. It is not at all exhaustive and only an initial draft.

```yaml
apiVersion: lunar.bank/v1beta1
kind: PostgreSQLInstance
metadata:
  name: user
spec:
  name: user
  configMapNamespace: dev
  storage: 1GB
  instanceTypes: m4.large
  # ...
```

The controller would then create the instance in RDS and create a config map with the required details, mainly the host name.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-rds-instance
  namespace: dev
data:
  db.host: some.host.com
