### ISSUE TITLE
Host credentials are fixed for the lifetime of the deployment

### ISSUE THREAD

**Issue by weberc2** [lunarway/postgresql-controller#82]
Once the postgresql-controller has been created, if additional instances are created or if the credentials for existing instances are changed (e.g., password rotation), there seems to be no way to manage them with postgresql-controller except to manually modify the postgresql-controller's deployment spec (to add the new instances' host credentials) and restart the postgresql-controller-controller-manager deployment.

Assuming the above assumption is correct, it seems like this is a common use case (creating new database instances after the postgresql-controller has been created).

A couple of possible solutions spring to mind:

* Add fields on the `PostgresqlDatabase` custom resource for the instance's admin credentials
    * Easier to implement
* Create a new `PostgresqlHostCredentials` custom resource which would have those same credentials
    * Seems better for password rotation

**Comment by Crevil** [comment]
That is the current constraint. Our use case has been few instances with many databases, so it hasn't bean that much of a hurdle.

I do however think a `PostgreSQLHostCredentials` resource would make sense going forward. 👍

**Comment by Crevil** [comment]
Can youn ellaborate a bit on your use case of instances compared to databases on the instance?

**Comment by weberc2** [comment]
My rationale (which I'm now second-guessing) is that it would be neater to keep an instance in each namespace rather than one instance which is shared by many applications. I was intending to use Kubegres to manage those instances, and ideally this controller would allow me to reference the secret into which Kubegres writes the admin credentials for a given cluster. Personally, I expect my own performance requirements could be met by a single instance, but certainly in larger companies I would expect to need many instances (perhaps with individual teams managing their own instances to avoid contention with other teams).

**Comment by Crevil** [comment]
Thanks. I agree that this would be a nice addition. Maybe something along the lines of this?
That would make it possible to reference both username and password from another resource.

How about the host name it self, is that also provided by kubegres?

```yaml
apiVersion: postgresql.lunar.tech/v1
kind: PostgreSQLHostCredentials
metadata:
  name: my-host
spec:
  host: my-host.default.svc.cluster.local.:5432
  user:
    value: iam_creator
  password:
    valueFrom:
      secretKeyRef:
        name: my-secret
        key: password
  params: sslmode=enabled
```
